services:
    php-fpm:
        container_name: obygnbe-container
        build:
            context: .
            dockerfile: ./docker/common/php-fpm/Dockerfile
            target: production
        image: "trahtechindo/obygnbe:latest"
        network_mode: bridge
        extra_hosts:
            - "host.docker.internal:host-gateway"
        restart: unless-stopped
        volumes:
            - obygnbe-volume:/var/www/storage
        env_file:
            - .env
        healthcheck:
            test: ["CMD-SHELL", "php-fpm-healthcheck || exit 1"]
            interval: 30s
            timeout: 10s
            retries: 3

volumes:
    obygnbe-volume:
